"""Voltando ao certo

Revision ID: 22f69aebaf3f
Revises: 9d162948aab9
Create Date: 2025-08-28 12:03:59.217020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f69aebaf3f'
down_revision = '9d162948aab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_migration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_migration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_migration_pkey'))
    )
    # ### end Alembic commands ###
