"""create tables

Revision ID: 655a88008fb7
Revises: 
Create Date: 2025-08-28 13:56:13.824773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655a88008fb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('profile_image_path', sa.String(length=300), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('master_profile',
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('began_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_table('player_characters',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('char_class', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('background', sa.String(length=100), nullable=False),
    sa.Column('alignement', sa.String(length=100), nullable=False),
    sa.Column('total_health', sa.Integer(), nullable=True),
    sa.Column('current_health', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('inventory',
    sa.Column('inv_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inv_id')
    )
    op.create_table('languages',
    sa.Column('lang_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('known_language', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lang_id')
    )
    op.create_table('master_characters',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('char_class', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('background', sa.String(length=100), nullable=False),
    sa.Column('alignement', sa.String(length=100), nullable=False),
    sa.Column('total_health', sa.Integer(), nullable=True),
    sa.Column('current_health', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('boss', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['master_profile.master_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('spells',
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.character_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spell_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    op.drop_table('skills')
    op.drop_table('master_characters')
    op.drop_table('languages')
    op.drop_table('inventory')
    op.drop_table('player_characters')
    op.drop_table('master_profile')
    op.drop_table('player_profile')
    op.drop_table('users')
    # ### end Alembic commands ###
