"""Migração para teste

Revision ID: 9d162948aab9
Revises: b73d8f795ef1
Create Date: 2025-08-28 12:02:16.511457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d162948aab9'
down_revision = 'b73d8f795ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_migration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_migration')
    # ### end Alembic commands ###
