"""Criação da estrutura inicial do banco

Revision ID: b73d8f795ef1
Revises: c340b5d9aed6
Create Date: 2025-08-21 14:21:39.985446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73d8f795ef1'
down_revision = 'c340b5d9aed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_teste_key'), type_='unique')
        batch_op.drop_column('teste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_teste_key'), ['teste'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
