"""Criação da estrutura inicial do banco

Revision ID: c340b5d9aed6
Revises: 
Create Date: 2025-08-21 14:17:58.798529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c340b5d9aed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('master_characters', schema=None) as batch_op:
        batch_op.alter_column('master_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('master_characters_master_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'master_profile', ['master_id'], ['master_id'], ondelete='CASCADE')

    with op.batch_alter_table('master_profile', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('player_characters', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('teste',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['teste'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('teste',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('player_characters', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('master_profile', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('master_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('master_characters_master_id_fkey'), 'player_profile', ['master_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('master_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
